---
- hosts: all
  tasks:
    - name: Install common software requirements
      yum:
        state: latest
        name:
        - amazon-linux-extras
        - java-1.8.0-openjdk*
        - tomcat-webapps
      become: yes
    - name: Install Nginx and Tomcat8.5 via amazon-linux-extras packages
      shell: "amazon-linux-extras install nginx1 tomcat8.5 -y"
      become: yes
    - name: Enable Nginx service
      service: name=nginx enabled=yes
      become: yes
    - name: Enable Tomcat service
      service: name=tomcat enabled=yes
      become: yes
    - name: Copy Nginx configuration file
      copy: src=nginx-sample.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
      become: yes